[package]
name = "swap"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["fs"] }
serde_json = "1.0"
lazy_static = "1.5.0"
rand = "0.8.5"
